// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recipe_Book.Models;

#nullable disable

namespace Recipe_Book.Migrations
{
    [DbContext(typeof(RecipesContext))]
    [Migration("20240619000450_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Recipe_Book.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Main Meal"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Deserts"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Appetizers"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Drinks"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Side Dishes"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Snacks"
                        });
                });

            modelBuilder.Entity("Recipe_Book.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Ingredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PreparationTime")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RecipeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CategoryId = 2,
                            Ingredients = "Eggs, Sugar, Flour, Cocoa, Baking Powder, Milk",
                            Instructions = "Mix all ingredients together till you get a smooth mixture. Bake it for 40-50 minutes, cool, and serve.",
                            Name = "Chocolate Cake",
                            PreparationTime = 60,
                            UserId = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            CategoryId = 1,
                            Ingredients = "Pasta, Tomato, Onion, Olive Oil, Salt, Water, Mushroom, Olives",
                            Instructions = "",
                            Name = "Pasta",
                            PreparationTime = 40,
                            UserId = 2
                        },
                        new
                        {
                            RecipeId = 3,
                            CategoryId = 1,
                            Ingredients = "",
                            Instructions = "",
                            Name = "Fish and Chips",
                            PreparationTime = 50,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Recipe_Book.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Password")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "Jana@gmail.com",
                            Name = "Jana",
                            Password = 1234
                        },
                        new
                        {
                            UserId = 2,
                            Email = "Raghad@gmail.com",
                            Name = "Raghad",
                            Password = 1234
                        },
                        new
                        {
                            UserId = 3,
                            Email = "Joud@gmail.com",
                            Name = "Joud",
                            Password = 1234
                        });
                });

            modelBuilder.Entity("Recipe_Book.Models.Recipe", b =>
                {
                    b.HasOne("Recipe_Book.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Recipe_Book.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
